"""Initial Migration

Revision ID: 2fac7cb653a2
Revises: 68fe00cd4f0f
Create Date: 2019-09-21 17:25:04.901244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fac7cb653a2'
down_revision = '68fe00cd4f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
