"""Initial Migration

Revision ID: 4de94f670f78
Revises: 0bd46dd5db38
Create Date: 2019-09-21 10:55:16.388361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de94f670f78'
down_revision = '0bd46dd5db38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.drop_column('users', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitch', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
