"""Initial Migration

Revision ID: 6f9cbcbfb05a
Revises: 2fac7cb653a2
Create Date: 2019-09-22 23:31:26.905133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9cbcbfb05a'
down_revision = '2fac7cb653a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('username', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('votes', sa.Integer(), nullable=True))
    op.drop_column('comments', 'feedback')
    op.add_column('votes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'user_id')
    op.add_column('comments', sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'votes')
    op.drop_column('comments', 'username')
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
